// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      _ref = AppView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppView.prototype.events = {
      "click .hit-button": function() {
        return this.model.get('currentPlayer').hit();
      },
      "click .stand-button": function() {
        return this.model.get('currentPlayer').stand();
      },
      "click .better": function(event) {
        this.toggleButtons();
        return this.model.get('currentPlayer').bet($(event.currentTarget).data('amount'));
      }
    };

    AppView.prototype.initialize = function() {
      var _this = this;
      this.listenTo(this.model, 'newRound', function() {
        return _this.toggleButtons();
      });
      return this.render();
    };

    AppView.prototype.toggleButtons = function() {
      return this.$('button').each(function(index, button) {
        button = $(button);
        if (button.attr('disabled')) {
          return button.removeAttr('disabled');
        } else {
          return button.attr('disabled', true);
        }
      });
    };

    AppView.prototype.render = function() {
      var _this = this;
      this.$el.children().detach();
      this.$el.append($('<button class="hit-button" disabled>Hit</button> <button class="stand-button" disabled>Stand</button>'));
      this.$el.append($('<button class="better bet10-button">Bet 10%</button>').data('amount', 10));
      this.$el.append($('<button class="better bet20-button">Bet 20%</button>').data('amount', 20));
      this.$el.append($('<button class="better bet50-button">Bet 50%</button>').data('amount', 50));
      this.$el.append($('<button class="better bet100-button">Bet 100%</button>').data('amount', 100));
      return (this.model.get('players')).each(function(player) {
        var container, playerView;
        container = (player.get('isDealer') ? '.deal' : '.play') + 'er-hand-container';
        playerView = new PlayerView({
          model: player
        });
        _this.$el.append($("<div class = " + container + " />").html(playerView.render()));
        return _this.$el;
      });
    };

    return AppView;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=AppView.map
*/
