// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.prototype.initialize = function() {
      var dealer, human, players,
        _this = this;
      this.set('deck', new Deck());
      players = new Players();
      human = new Player({
        name: 'player',
        isDealer: false
      });
      dealer = new Player({
        name: 'dealer',
        isDealer: true
      });
      players.add([human, dealer]);
      players.each(function(player) {
        return _this.giveCards(player);
      });
      this.set('currentPlayer', players.first());
      this.set('players', players);
      return this.listenTo(this.get('players'), 'I_want_to_hit', function(player) {
        _this.addCardToPlayer(player);
        return _this.nextTurn(player);
      });
    };

    App.prototype.giveCards = function(player) {
      var deck;
      deck = this.get('deck');
      (player.get('hand')).add(deck.pop());
      (player.get('hand')).add(deck.pop());
      if (player.get('isDealer')) {
        return (player.get('hand')).at(0).flip();
      }
    };

    App.prototype.addCardToPlayer = function(player) {
      return (this.get('deck')).hitPlayer(player);
    };

    App.prototype.nextTurn = function() {
      var everyoneIsBusted, index;
      index = (this.get('players')).models.indexOf(this.get('currentPlayer'));
      this.set('currentPlayer', (this.get('players')).at(index + 1) || (this.get('players')).first());
      if ((this.get('currentPlayer')).get('busted')) {
        everyoneIsBusted = (this.get('players')).all(function(player) {
          return player.get('busted');
        });
        if (everyoneIsBusted) {
          alert('GAME ENDED MUTHAFUCKAS');
          return this;
        } else {
          return this.nextTurn();
        }
      } else {
        if ((this.get('currentPlayer')).get('isDealer')) {
          return (this.get('currentPlayer')).hit();
        }
      }
    };

    return App;

  })(Backbone.Model);

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
