// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.prototype.initialize = function() {
      var _this = this;
      this.set('deck', new Deck());
      this.set('players', new Players());
      (this.get('players')).add([
        new Player({
          player: 'player',
          isDealer: false
        }), new Player({
          player: 'dealer',
          isDealer: true
        })
      ]);
      (this.get('players')).each(function(player) {
        return _this.giveCards(player);
      });
      return this.set('currentPlayer', (this.get('players')).first());
    };

    App.prototype.giveCards = function(player) {
      var deck, hand;
      deck = this.get('deck');
      hand = new Hand([deck.pop(), deck.pop()]);
      return player.set('hand', hand);
    };

    return App;

  })(Backbone.Model);

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
