// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    return new AppView({
      model: new App()
    }).$el.appendTo('body');
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
